version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_payments
    columns:
      - name: payment_status
        tests:
          - accepted_values:
                values: ['success','fail']